### ISSUE TITLE
Add TOC sidebar for manual.md

### ISSUE THREAD

**Issue by clemens-tolboom** [denoland/deno_website2#240]
Comparing https://deno.land/typedoc/ with https://deno.land/std/manual.md a sidebar for the TOC would be great. I guess a PR should mimic the sidebar of https://deno.land/typedoc/

My fiddlle on a big screen was useful enough to navigate.

```css
ul.style {
    position: fixed;
    top: 2vh;
    left: 1em;
    max-width: 17em;
    scroll-behavior: auto;
    max-height: 90vh;
    overflow-y: scroll;
}
```
